# Generated by Django 2.2.24 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name_plural': 'Квартиры'},
        ),
    ]
