# Generated by Django 2.2.24 on 2023-07-29 20:57

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if(phonenumbers.is_valid_number(owner_pure_phone)):
            defaults = {'owner_pure_phone': owner_pure_phone}
        else:
            defaults = {'owners_phonenumber': ''}
        Flat.objects.update_or_create(id=flat.id, defaults=defaults)


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update_or_create(
        id=flat.id,
        defaults={'owner_pure_phone': PhoneNumber()}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
